const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const REQUEST_INCREMENT = 'REQUEST_INCREMENT';
const REQUEST_DECREMENT = 'REQUEST_DECREMENT';

const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

export const Constants = {
  INCREMENT,
  DECREMENT,
  REQUEST_INCREMENT,
  REQUEST_DECREMENT,
  CHANGE_NAME,
  CHANGE_PASSWORD,
  LOGIN,
  LOGOUT
};