const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const REQUEST_INCREMENT = 'REQUEST_INCREMENT';
const REQUEST_DECREMENT = 'REQUEST_DECREMENT';

const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

const REQUEST_LOGIN = 'REQUEST_LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGGING_IN = 'LOGGING_IN';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

export const Constants = {
  INCREMENT,
  DECREMENT,
  REQUEST_INCREMENT,
  REQUEST_DECREMENT,
  CHANGE_NAME,
  CHANGE_PASSWORD,
  REQUEST_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGGING_IN,
  LOGIN,
  LOGOUT
};
